### ISSUE TITLE
请教，数据嵌套的情况如何解析？

### ISSUE THREAD

**Issue by mxpasser** [debugly/SCJSONUtil#1]
@debugly 
建议加上model 2 json。。。这样就可以相互转了。。。😄

有个问题请教，如果数据有嵌套怎么处理，比如有数组嵌套，字典嵌套？

比如数据是这样的里面的数据全都需要，其中想在model里加一个array属性然后直接访问该array，array里都是ViewNoRepaymentBillList中对应的model，这个如何处理。谢谢。

//RepaymentAmount = "4164.57";
//RepaymentPeriodsAccount = 3;
//ViewNoRepaymentBillList =         (
//                                   {
//                                       OverdueDays = 0;
//                                       RepaymentAmount = "1388.19";
//  
//                                       RepaymentDate = "2016-08-14";
//                                       RepaymentPeriods = 4;
//                                       RepaymentStatus = "待扣款";
//                                   },
//                                   {
//                                       OverdueDays = 0;
//                                       RepaymentAmount = "1388.19";
//                                       RepaymentDate = "2016-09-14";
//                                       RepaymentPeriods = 5;
//                                       RepaymentStatus = "待扣款";
//                                   })

**Comment by debugly** [comment]
> 暂时没有 model 转 json 的需求，所以没提供；

把字典里的 json 数组，解析成 model 数组是支持的！你看下我的解析例子吧，详见 DataInfoModel  类里有个 carInfoArr 数组，最终会被解析为 model 数组的，有不清楚的了，可以再问我

``` objc
@implementation DataInfoModel

- (NSDictionary *)collideKeyModelMap
{
    return @{@"basic":@"BasicInfoModel",@"cars":@"CarInfoModel"};
}

- (NSDictionary *)collideKeysMap
{
    return @{@"basic":@"basicInfo",@"cars":@"carInfoArr"};
}

@end
```

解释下：
cars 是 json 数组，carInfoArr 是 model 类的一个数组属性；

basic 是 json 字典，basicInfo 是 model 类的一个属性（一个子model）；

这个例子里 json 嵌套了好几层呢。。。

**Comment by mxpasser** [comment]
@debugly 谢谢你的回复。后来我试了几次出来了，很方便。 
有个地方，如果数据返回的是ViewNoRepaymentBillList  = ( ) 空数组的时候解析出来的数组会返回nil，这里返回一个空数组会好点。
