### ISSUE TITLE
iPhone 5 真机上出现崩溃

### ISSUE THREAD

**Issue by mxpasser** [debugly/SCJSONUtil#2]
@debugly hi，一直用这个工具类，最近出现了转换崩溃的地方，主要是iPhone 5 手机上出现崩溃，6及以上手机都没事。
<img width="527" alt="tmp001d9038" src="https://cloud.githubusercontent.com/assets/3272620/20744817/ff1c0d10-b718-11e6-8a8f-edecc601bf21.png">
我们定了一个字段为BOOL类型，后端将该字段返回值为数字1，这时候，jsonutil 会执行nsnumber这一步的解析，将数字转成string，结果跟我们定义的BOOL类型匹配不上了，应该就出现崩溃了

**Comment by debugly** [comment]
额，很抱歉，给你造成了麻烦，这个应该是系统的 KVC 没有处理好;
这个小框架对 NSString 的支持很好,我的建议是**将BOOL类型改为NSString类型**；
比如将你现在的 BOOL 改为：NSString *vip，在业务逻辑上使用: [vip boolValue]; 做判断即可；

**Comment by mxpasser** [comment]
@debugly 好的，谢谢回复。
